version: '3.8'

services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: kpi-redis-test
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - kpi-network
    restart: unless-stopped

  # Backend API
  backend:
    image: kpi-backend:test
    container_name: kpi-backend-test
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_AVAILABLE=true
      - SECRET_KEY=test_secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - kpi-network
    restart: unless-stopped

networks:
  kpi-network:
    driver: bridge