version: '3.8'

services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: kpi-redis-dev
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dev:/data
    ports:
      - "6379:6379"
    networks:
      - kpi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: kpi-backend-dev
    environment:
      - DATABASE_URL=postgresql://dashboard_user:${DB_PASSWORD:-your_password}@postgres:5432/mmtg_dashboard
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_AVAILABLE=true
      - SECRET_KEY=${SECRET_KEY:-your_secret_key}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8000:3000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - kpi-network
    restart: unless-stopped
    volumes:
      - ../backend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: kpi-frontend-dev
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - kpi-network
    restart: unless-stopped

networks:
  kpi-network:
    driver: bridge

volumes:
  redis_data_dev: